### ISSUE TITLE
Dotfiles are not free

### ISSUE THREAD

**Issue by JohnAgapeyev** [isaacmorneau/dotfiles#4]
This repo needs a license, as otherwise it defaults to the creator having all copyright claims.
Other people should not be sued for using your Dotfiles.
And neither should someone be able to modify your Dotfiles without you being able to see the changes/improvements they have made.

For these reasons I strongly urge you to adopt the GNU General Public License Version 3, available at https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by JulianWebb** [comment]
I believe these dotfiles should be closed source and that a fee should be charged for their use.

**Comment by JulianWebb** [comment]
On second thought, since these dotfiles are derived from the default configs included in their respective programs, there might be license conflicts. I propose that the 1.0 release be taken down until the licensing issue is resolved

**Comment by isaacmorneau** [comment]
Releases as it turns out are permanent and cannot be deleted. My hands are tied.

**Comment by JulianWebb** [comment]
There is one way, delete the entire repo.
